import '@/styles/tailwind.css';
import type { Metadata } from 'next';
import { Onest } from 'next/font/google';
import { Layout } from '@/components/Layout';

const onest = Onest({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s - Sara Cosmai',
    default: 'Sara Cosmai - Product Designer',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${onest.className} bg-slate-950`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
