import '@/styles/tailwind.css';
import type { Metadata } from 'next';
import { Onest } from 'next/font/google';
import { Layout } from '@/components/layout/Layout';
import { HotjarSnippet } from '@/components/HotjarSnippet';

const onest = Onest({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s - Sara Cosmai',
    default: 'Sara Cosmai - Product Designer',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={`${onest.className} selection:bg-orange-accent bg-slate-950 selection:text-orange-950`}
      >
        <Layout>{children}</Layout>
        <HotjarSnippet />
      </body>
    </html>
  );
}
